stages:
  - build
variables:
  DOCKER_REGISTRY: git-registry.thm.de
  DOCKER_IMAGE_NAME: amine/service-details

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - echo "Building Docker image..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $DOCKER_REGISTRY
    - docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME .
    - docker push $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME

